### ISSUE TITLE
Binary verification documentation discussion

### ISSUE THREAD

**Issue by qubenix** [erciccione/monero-documentation#5]
I thought it was best to start an issue to continue discussion from #4. There's no reason to hold up that PR on this.

Here's what I've been working on for binary verification documentation: https://github.com/qubenix/monero-documentation/blob/qubenix-verify1/binary-verification.md. I tried to keep is as short as possible. I still think it's best to have this as its own guide and just link to it from the GUI guide.

I used the verification documentation from various security focused projects as inspiration, trying to keep it as short and simple as possible.

https://www.whonix.org/wiki/Whonix_Signing_Key
https://www.whonix.org/wiki/VirtualBox/Verify_the_virtual_machine_images_using_the_command_line
https://wiki.archlinux.org/index.php/Category:Getting_and_installing_Arch
https://www.qubes-os.org/security/verifying-signatures/
https://www.torproject.org/docs/verifying-signatures
https://tails.boum.org/install/download/
https://gnupg.org/download/integrity_check.html

**Comment by erciccione** [comment]
Now that i see the finished guide i agree with you, would be better to put it on the website and link to it from the guide. Let's wait for feedbacks about this matter, if nobody has a strong opinion on this, we can just do it as you suggested.

**Comment by erciccione** [comment]
From Freenode (#monero-community)
```
<dEBRUYNE> ErCiccione: That needs some improvement for Windows (the guide)
<dEBRUYNE> Windows users are not going to be able to follow that :p
<dEBRUYNE> re: adding it to the website and linking, fine with me
<ErCiccione> dEBRUYNE: i agree, also would be probably better to avoid the terminal on windows. I will report your suggestions
```
Probably would be better to make a guide based only on GUI tools for windows, like Kleopatra

**Comment by qubenix** [comment]
Thanks for the feedback! So it sounds like it's going to be a better idea to break Windows out into it's own guide, maybe a guide for each OS since Mac users will want to do as much as possible through `Finder`. I can start working on it today (when I have extra time) and hopefully have something to look at later.

**Comment by qubenix** [comment]
Here's what I've been working on for the Windows guide: https://github.com/qubenix/monero-documentation/blob/qubenix-verify1/windows-verification-guide.md.

At first I was going back and forth on how verbose to be, but ultimately I decided to just document every little thing. We can remove some later if it becomes too long/daunting.

**Comment by qubenix** [comment]
The windows draft is finished, we can do modifications from here. In the final section I have the guide instruct to use the terminal for calculating the sha256 hash. Windows has no built in gui for sha256 hashing, just sha1. So it's either use the command line for one thing or install more software and document that whole process. I'm interested in thoughts.

https://github.com/qubenix/monero-documentation/blob/qubenix-verify1/windows-verification-guide.md

**Comment by erciccione** [comment]
I like it, very accurate. What do you think about putting an index at the beginning? The document is quite long, That would make it easier to use

**Comment by qubenix** [comment]
Take a look now. I added a table of contents and cleaned it up a bit. 

It would be nice if a Windows user could follow the guide and give feedback, even nicer on Windows 10 since I only have 7 in a VM.

**Comment by erciccione** [comment]
I cannot test it on win10 but it looks good. You can open a PR to add the guide for the verification on the website, so people can test it directly from there.

**Comment by qubenix** [comment]
Will do!
